version: '3'
services:
  ruby-container:
    build: ./
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      BUNDLE_APP_CONFIG: 
      BUNDLE_PATH: 
      BUNDLE_BIN:
      BUNDLE_SILENCE_ROOT_WARNING:
    command: bundle install --path /bundle
volumes:
    bundle:
      driver: local