version: '3'
services:
  myapp:
    build: ./
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RUBYOPT: -EUTF-8
    command: bundle install
volumes:
    bundle:
      driver: local